on:
  push:
    branches:
      - master

name: Deploy to Dokku on push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Dokku
        run: ./.github/git-push.sh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          TARGET_GIT_URL: ${{ secrets.TARGET_GIT_URL }}
